import { Button, VerticalBox, LineEdit, GridLayout, Rectangle, Text } from "std-widgets.slint";

export component AppWindow inherits Window {
    in property <string> results: "";
    callback divide-income(string, string);
    in-out property <bool> open_curtain;
    animate background { duration: 800ms; }

    background: #313e50;

    GridLayout {
        padding: 50px;
        spacing: 25px;
        Row {
            LineEdit {
                id: name_input;
                placeholder-text: "Enter your name:";
                font-size: 16px;
                height: 35px;
                horizontal-alignment: center;
            }
        }
        Row {
            LineEdit {
                id: message_input;
                placeholder-text: "Enter your message:";
                font-size: 16px;
                height: 35px;
                horizontal-alignment: center;
            }
        }
        Row {
            Button {
                text: "Show";
                padding-top: 30px;
                height: 35px;
                primary: true;
                clicked => {
                    root.open_curtain = !root.open_curtain;
                    root.divide-income(name_input.text, message_input.text);
                }
            }
        }
        Row {
            VerticalBox {
                Rectangle {
                    height: 100px;
                    background: #f2f2f2;
                    Text {
                        text: root.results;
                        font-size: 16px;
                        color: #000000;
                        font-weight: 500;
                    }
                }
            }
        }
    }
}
